#include <iostream>

int leave() { exit(0); return 1; }
int main() {
for (int f0 = 1; f0<256; f0++ )
 if (f0 % 2 == 0)
  for (int f1 = f0; f1<256; f1++ )
   if (f1 % 3 == 0)
    for (int f2 = f1; f2<256; f2++ )
     if (f2 % 4 == 0)
      for (int f3 = f2; f3<256; f3++ )
       if (f3 % 5 == 0)
        for (int f4 = f3; f4<256; f4++ )
         if (f4 % 6 == 0)
          for (int f5 = f4; f5<256; f5++ )
           if (f5 % 7 == 0)
            for (int f6 = f5; f6<256; f6++ )
             if (f6 % 8 == 0)
              for (int f7 = f6; f7<256; f7++ )
               if (f7 % 9 == 0)
                for (int f8 = f7; f8<256; f8++ )
                 if (f8 % 10 == 0)
                  for (int f9 = f8; f9<256; f9++ )
                   if (f9 % 11 == 0)
                    for (int f10 = f9; f10<256; f10++ )
                     if (f10 % 12 == 0)
                      for (int f11 = f10; f11<256; f11++ )
                       if (f11 % 13 == 0)
                        for (int f12 = f11; f12<256; f12++ )
                         if (f12 % 14 == 0)
                          for (int f13 = f12; f13<256; f13++ )
                           if (f13 % 15 == 0)
                            for (int f14 = f13; f14<256; f14++ )
                             if (f14 % 16 == 0)
                              for (int f15 = f14; f15<256; f15++ )
                               if (f15 % 17 == 0)
                                for (int f16 = f15; f16<256; f16++ )
                                 if (f16 % 18 == 0)
                                  for (int f17 = f16; f17<256; f17++ )
                                   if (f17 % 19 == 0)
                                    for (int f18 = f17; f18<256; f18++ )
                                     if (f18 % 20 == 0)
                                      for (int f19 = f18; f19<256; f19++ )
                                       if (f19 % 21 == 0)
                                        for (int f20 = f19; f20<256; f20++ )
                                         if (f20 % 22 == 0)
                                          for (int f21 = f20; f21<256; f21++ )
                                           if (f21 % 23 == 0)
                                            for (int f22 = f21; f22<256; f22++ )
                                             if (f22 % 24 == 0)
                                              for (int f23 = f22; f23<256; f23++ )
                                               if (f23 % 25 == 0)
                                                for (int f24 = f23; f24<256; f24++ )
                                                 if (f24 % 26 == 0)
                                                  for (int f25 = f24; f25<256; f25++ )
                                                   if (f25 % 27 == 0)
                                                    for (int f26 = f25; f26<256; f26++ )
                                                     if (f26 % 28 == 0)
                                                      for (int f27 = f26; f27<256; f27++ )
                                                       if (f27 % 29 == 0)
                                                        for (int f28 = f27; f28<256; f28++ )
                                                         if (f28 % 30 == 0)
                                                          for (int f29 = f28; f29<256; f29++ )
                                                           if (f29 % 31 == 0)
                                                            for (int f30 = f29; f30<256; f30++ )
                                                             if (f30 % 32 == 0)
                                                              for (int f31 = f30; f31<256; f31++ )
                                                               if (f31 % 33 == 0)
                                                                for (int f32 = f31; f32<256; f32++ )
                                                                 if (f32 % 34 == 0)
                                                                  for (int f33 = f32; f33<256; f33++ )
                                                                   if (f33 % 35 == 0)
                                                                    for (int f34 = f33; f34<256; f34++ )
                                                                     if (f34 % 36 == 0)
                                                                      for (int f35 = f34; f35<256; f35++ )
                                                                       if (f35 % 37 == 0)
                                                                        for (int f36 = f35; f36<256; f36++ )
                                                                         if (f36 % 38 == 0)
                                                                          for (int f37 = f36; f37<256; f37++ )
                                                                           if (f37 % 39 == 0)
                                                                            for (int f38 = f37; f38<256; f38++ )
                                                                             if (f38 % 40 == 0)
                                                                              for (int f39 = f38; f39<256; f39++ )
                                                                               if (f39 % 41 == 0)
                                                                                for (int f40 = f39; f40<256; f40++ )
                                                                                 if (f40 % 42 == 0)
                                                                                  for (int f41 = f40; f41<256; f41++ )
                                                                                   if (f41 % 43 == 0)
                                                                                    for (int f42 = f41; f42<256; f42++ )
                                                                                     if (f42 % 44 == 0)
                                                                                      for (int f43 = f42; f43<256; f43++ )
                                                                                       if (f43 % 45 == 0)
                                                                                        for (int f44 = f43; f44<256; f44++ )
                                                                                         if (f44 % 46 == 0)
                                                                                          for (int f45 = f44; f45<256; f45++ )
                                                                                           if (f45 % 47 == 0)
                                                                                            for (int f46 = f45; f46<256; f46++ )
                                                                                             if (f46 % 48 == 0)
                                                                                              for (int f47 = f46; f47<256; f47++ )
                                                                                               if (f47 % 49 == 0)
                                                                                                for (int f48 = f47; f48<256; f48++ )
                                                                                                 if (f48 % 50 == 0)
                                                                                                  for (int f49 = f48; f49<256; f49++ )
                                                                                                   if (f49 % 51 == 0)
                                                                                                    for (int f50 = f49; f50<256; f50++ )
                                                                                                     if (f50 % 52 == 0)
                                                                                                      for (int f51 = f50; f51<256; f51++ )
                                                                                                       if (f51 % 53 == 0)
                                                                                                        for (int f52 = f51; f52<256; f52++ )
                                                                                                         if (f52 % 54 == 0)
                                                                                                          for (int f53 = f52; f53<256; f53++ )
                                                                                                           if (f53 % 55 == 0)
                                                                                                            for (int f54 = f53; f54<256; f54++ )
                                                                                                             if (f54 % 56 == 0)
                                                                                                              for (int f55 = f54; f55<256; f55++ )
                                                                                                               if (f55 % 57 == 0)
                                                                                                                for (int f56 = f55; f56<256; f56++ )
                                                                                                                 if (f56 % 58 == 0)
                                                                                                                  for (int f57 = f56; f57<256; f57++ )
                                                                                                                   if (f57 % 59 == 0)
                                                                                                                    for (int f58 = f57; f58<256; f58++ )
                                                                                                                     if (f58 % 60 == 0)
                                                                                                                      for (int f59 = f58; f59<256; f59++ )
                                                                                                                       if (f59 % 61 == 0)
                                                                                                                        for (int f60 = f59; f60<256; f60++ )
                                                                                                                         if (f60 % 62 == 0)
                                                                                                                          for (int f61 = f60; f61<256; f61++ )
                                                                                                                           if (f61 % 63 == 0)
                                                                                                                            for (int f62 = f61; f62<256; f62++ )
                                                                                                                             if (f62 % 64 == 0)
                                                                                                                              for (int f63 = f62; f63<256; f63++ )
                                                                                                                               if (f63 % 65 == 0)
                                                                                                                                for (int f64 = f63; f64<256; f64++ )
                                                                                                                                 if (f64 % 66 == 0)
                                                                                                                                  for (int f65 = f64; f65<256; f65++ )
                                                                                                                                   if (f65 % 67 == 0)
                                                                                                                                    for (int f66 = f65; f66<256; f66++ )
                                                                                                                                     if (f66 % 68 == 0)
                                                                                                                                      for (int f67 = f66; f67<256; f67++ )
                                                                                                                                       if (f67 % 69 == 0)
                                                                                                                                        for (int f68 = f67; f68<256; f68++ )
                                                                                                                                         if (f68 % 70 == 0)
                                                                                                                                          for (int f69 = f68; f69<256; f69++ )
                                                                                                                                           if (f69 % 71 == 0)
                                                                                                                                            for (int f70 = f69; f70<256; f70++ )
                                                                                                                                             if (f70 % 72 == 0)
                                                                                                                                              for (int f71 = f70; f71<256; f71++ )
                                                                                                                                               if (f71 % 73 == 0)
                                                                                                                                                for (int f72 = f71; f72<256; f72++ )
                                                                                                                                                 if (f72 % 74 == 0)
                                                                                                                                                  for (int f73 = f72; f73<256; f73++ )
                                                                                                                                                   if (f73 % 75 == 0)
                                                                                                                                                    for (int f74 = f73; f74<256; f74++ )
                                                                                                                                                     if (f74 % 76 == 0)
                                                                                                                                                      for (int f75 = f74; f75<256; f75++ )
                                                                                                                                                       if (f75 % 77 == 0)
                                                                                                                                                        for (int f76 = f75; f76<256; f76++ )
                                                                                                                                                         if (f76 % 78 == 0)
                                                                                                                                                          for (int f77 = f76; f77<256; f77++ )
                                                                                                                                                           if (f77 % 79 == 0)
                                                                                                                                                            for (int f78 = f77; f78<256; f78++ )
                                                                                                                                                             if (f78 % 80 == 0)
                                                                                                                                                              for (int f79 = f78; f79<256; f79++ )
                                                                                                                                                               if (f79 % 81 == 0)
                                                                                                                                                                for (int f80 = f79; f80<256; f80++ )
                                                                                                                                                                 if (f80 % 82 == 0)
                                                                                                                                                                  for (int f81 = f80; f81<256; f81++ )
                                                                                                                                                                   if (f81 % 83 == 0)
                                                                                                                                                                    for (int f82 = f81; f82<256; f82++ )
                                                                                                                                                                     if (f82 % 84 == 0)
                                                                                                                                                                      for (int f83 = f82; f83<256; f83++ )
                                                                                                                                                                       if (f83 % 85 == 0)
                                                                                                                                                                        for (int f84 = f83; f84<256; f84++ )
                                                                                                                                                                         if (f84 % 86 == 0)
                                                                                                                                                                          for (int f85 = f84; f85<256; f85++ )
                                                                                                                                                                           if (f85 % 87 == 0)
                                                                                                                                                                            for (int f86 = f85; f86<256; f86++ )
                                                                                                                                                                             if (f86 % 88 == 0)
                                                                                                                                                                              for (int f87 = f86; f87<256; f87++ )
                                                                                                                                                                               if (f87 % 89 == 0)
                                                                                                                                                                                for (int f88 = f87; f88<256; f88++ )
                                                                                                                                                                                 if (f88 % 90 == 0)
                                                                                                                                                                                  for (int f89 = f88; f89<256; f89++ )
                                                                                                                                                                                   if (f89 % 91 == 0)
                                                                                                                                                                                    for (int f90 = f89; f90<256; f90++ )
                                                                                                                                                                                     if (f90 % 92 == 0)
                                                                                                                                                                                      for (int f91 = f90; f91<256; f91++ )
                                                                                                                                                                                       if (f91 % 93 == 0)
                                                                                                                                                                                        for (int f92 = f91; f92<256; f92++ )
                                                                                                                                                                                         if (f92 % 94 == 0)
                                                                                                                                                                                          for (int f93 = f92; f93<256; f93++ )
                                                                                                                                                                                           if (f93 % 95 == 0)
                                                                                                                                                                                            for (int f94 = f93; f94<256; f94++ )
                                                                                                                                                                                             if (f94 % 96 == 0)
                                                                                                                                                                                              for (int f95 = f94; f95<256; f95++ )
                                                                                                                                                                                               if (f95 % 97 == 0)
                                                                                                                                                                                                for (int f96 = f95; f96<256; f96++ )
                                                                                                                                                                                                 if (f96 % 98 == 0)
                                                                                                                                                                                                  for (int f97 = f96; f97<256; f97++ )
                                                                                                                                                                                                   if (f97 % 99 == 0)
                                                                                                                                                                                                    for (int f98 = f97; f98<256; f98++ )
                                                                                                                                                                                                     if (f98 % 100 == 0)
                                                                                                                                                                                                      for (int f99 = f98; f99<256; f99++ )
                                                                                                                                                                                                       if (f99 % 101 == 0)
                                                                                                                                                                                                        for (int f100 = f99; f100<256; f100++ )
                                                                                                                                                                                                         if (f100 % 102 == 0)
                                                                                                                                                                                                          for (int f101 = f100; f101<256; f101++ )
                                                                                                                                                                                                           if (f101 % 103 == 0)
                                                                                                                                                                                                            for (int f102 = f101; f102<256; f102++ )
                                                                                                                                                                                                             if (f102 % 104 == 0)
                                                                                                                                                                                                              for (int f103 = f102; f103<256; f103++ )
                                                                                                                                                                                                               if (f103 % 105 == 0)
                                                                                                                                                                                                                for (int f104 = f103; f104<256; f104++ )
                                                                                                                                                                                                                 if (f104 % 106 == 0)
                                                                                                                                                                                                                  for (int f105 = f104; f105<256; f105++ )
                                                                                                                                                                                                                   if (f105 % 107 == 0)
                                                                                                                                                                                                                    for (int f106 = f105; f106<256; f106++ )
                                                                                                                                                                                                                     if (f106 % 108 == 0)
                                                                                                                                                                                                                      for (int f107 = f106; f107<256; f107++ )
                                                                                                                                                                                                                       if (f107 % 109 == 0)
                                                                                                                                                                                                                        for (int f108 = f107; f108<256; f108++ )
                                                                                                                                                                                                                         if (f108 % 110 == 0)
                                                                                                                                                                                                                          for (int f109 = f108; f109<256; f109++ )
                                                                                                                                                                                                                           if (f109 % 111 == 0)
                                                                                                                                                                                                                            for (int f110 = f109; f110<256; f110++ )
                                                                                                                                                                                                                             if (f110 % 112 == 0)
                                                                                                                                                                                                                              for (int f111 = f110; f111<256; f111++ )
                                                                                                                                                                                                                               if (f111 % 113 == 0)
                                                                                                                                                                                                                                for (int f112 = f111; f112<256; f112++ )
                                                                                                                                                                                                                                 if (f112 % 114 == 0)
                                                                                                                                                                                                                                  for (int f113 = f112; f113<256; f113++ )
                                                                                                                                                                                                                                   if (f113 % 115 == 0)
                                                                                                                                                                                                                                    for (int f114 = f113; f114<256; f114++ )
                                                                                                                                                                                                                                     if (f114 % 116 == 0)
                                                                                                                                                                                                                                      for (int f115 = f114; f115<256; f115++ )
                                                                                                                                                                                                                                       if (f115 % 117 == 0)
                                                                                                                                                                                                                                        for (int f116 = f115; f116<256; f116++ )
                                                                                                                                                                                                                                         if (f116 % 118 == 0)
                                                                                                                                                                                                                                          for (int f117 = f116; f117<256; f117++ )
                                                                                                                                                                                                                                           if (f117 % 119 == 0)
                                                                                                                                                                                                                                            for (int f118 = f117; f118<256; f118++ )
                                                                                                                                                                                                                                             if (f118 % 120 == 0)
                                                                                                                                                                                                                                              for (int f119 = f118; f119<256; f119++ )
                                                                                                                                                                                                                                               if (f119 % 121 == 0)
                                                                                                                                                                                                                                                for (int f120 = f119; f120<256; f120++ )
                                                                                                                                                                                                                                                 if (f120 % 122 == 0)
                                                                                                                                                                                                                                                  for (int f121 = f120; f121<256; f121++ )
                                                                                                                                                                                                                                                   if (f121 % 123 == 0)
                                                                                                                                                                                                                                                    for (int f122 = f121; f122<256; f122++ )
                                                                                                                                                                                                                                                     if (f122 % 124 == 0)
                                                                                                                                                                                                                                                      for (int f123 = f122; f123<256; f123++ )
                                                                                                                                                                                                                                                       if (f123 % 125 == 0)
                                                                                                                                                                                                                                                        for (int f124 = f123; f124<256; f124++ )
                                                                                                                                                                                                                                                         if (f124 % 126 == 0)
                                                                                                                                                                                                                                                          for (int f125 = f124; f125<256; f125++ )
                                                                                                                                                                                                                                                           if (f125 % 127 == 0)
                                                                                                                                                                                                                                                            for (int f126 = f125; f126<256; f126++ )
                                                                                                                                                                                                                                                             if (f126 % 128 == 0)
                                                                                                                                                                                                                                                              for (int f127 = f126; f127<256; f127++ )
                                                                                                                                                                                                                                                               if (f127 % 129 == 0)
                                                                                                                                                                                                                                                                std::cout << (f127 - 1) * 2 << std::endl << leave();
}
